language: r
sudo: false
cache: packages

warnings_are_errors: true
bioc_required: true

r_packages:
  - covr

r_github_packages:
  - sgibb/topdowndata

bioc_packages:
  - BiocStyle

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
