language: r
sudo: required
dist: trusty
cache: packages

r: bioc-devel

warnings_are_errors: true

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 [xerus] it is part of libnetcdf-dev)
      - libhdf5-dev

r_packages:
  - covr
  - pkgdown

r_github_packages:
  - sgibb/topdownrdata

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
