language: r
sudo: false
cache: packages

r: bioc-devel

warnings_are_errors: true

r_packages:
  - covr

r_github_packages:
  - sgibb/topdowndata

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
